version: "2"
services:
  db:
    image: postgres:9.6
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: smshandler_db
      POSTGRES_PASSWORD: devpass
    volumes:
      - ./.pgdata/:/var/lib/postgresql/data/pgdata/
    expose:
      - "5432"

  webapp:
    build:
      context: .
    image: sms-handler
    environment:
      DJANGO_SETTINGS_MODULE: webapp.settings
      SECRET_KEY: devkey
      DATABASE_URL: postgres://postgres:devpass@db:5432/smshandler_db